package Program;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class form_DataKaryawan extends javax.swing.JFrame {
    
    public form_DataKaryawan() {
        initComponents();
        tampil();
        
    }   
    

    
    //instansi of class koneksi_database
    koneksi_database kon = new koneksi_database();
    int ID = 0;
    String Status_Diri = "";
    
    private void tampil(){
        DefaultTableModel model_tblKaryawan = new DefaultTableModel();
        model_tblKaryawan.addColumn("ID ");
        model_tblKaryawan.addColumn("Nama");
        model_tblKaryawan.addColumn("Tempat Lahir");
        model_tblKaryawan.addColumn("TTL");
        model_tblKaryawan.addColumn("Pendidikan");
        model_tblKaryawan.addColumn("Status");
        model_tblKaryawan.addColumn("Status Diri");
        tbl_DataKaryawan.setModel(model_tblKaryawan);
        try {
            kon.res = kon.stat.executeQuery("SELECT * FROM `data_karyawan`");
                     
            while(kon.res.next()){  
                model_tblKaryawan.addRow(new Object[]{
                    kon.res.getString(1),
                    kon.res.getString(2),
                    kon.res.getString(3),
                    kon.res.getString(4),
                    kon.res.getString(5),                                        
                    kon.res.getString(6),
                    kon.res.getString(7)
                });
                tbl_DataKaryawan.setModel(model_tblKaryawan);
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan Error : "+e);
        }
  } 
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup_Status = new javax.swing.ButtonGroup();
        lbl_Judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        txt_TempatLahir = new javax.swing.JTextField();
        txt_TTL = new javax.swing.JTextField();
        cmb_Pendidikan = new javax.swing.JComboBox<>();
        cmb_Status = new javax.swing.JComboBox<>();
        btn_Tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DataKaryawan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Hasil = new javax.swing.JTextArea();
        rb_Mahsiswa = new javax.swing.JRadioButton();
        rb_Menikah = new javax.swing.JRadioButton();
        label_7 = new javax.swing.JLabel();
        btn_Edit = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Judul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Judul.setText("FORM DATA KARYAWAN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nama   :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tempat Lahir :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tgl-Bln-Lahir   :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pendidikan :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Status Karyawan :");

        cmb_Pendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "S1", "S2", "D3", "D4" }));

        cmb_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kontrak", "Tetap" }));

        btn_Tambah.setText("Tambah");
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        tbl_DataKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Title 3", "Title 4", "Tambahan"
            }
        ));
        tbl_DataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DataKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DataKaryawan);

        txt_Hasil.setColumns(20);
        txt_Hasil.setRows(5);
        jScrollPane2.setViewportView(txt_Hasil);

        grup_Status.add(rb_Mahsiswa);
        rb_Mahsiswa.setText("Mahasiswa");

        grup_Status.add(rb_Menikah);
        rb_Menikah.setText("Menikah");

        label_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_7.setText("Status ");

        btn_Edit.setText("EDIT");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Hapus.setText("HAPUS");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        jLabel6.setText("Cari Nama : ");

        txt_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lbl_Judul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(58, 58, 58)
                                        .addComponent(txt_Nama))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(21, 21, 21)
                                        .addComponent(txt_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(54, 54, 54)
                                        .addComponent(cmb_Pendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_TTL, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_7)
                                        .addGap(77, 77, 77)
                                        .addComponent(rb_Menikah)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_Mahsiswa))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbl_Judul)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cmb_Pendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_TTL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_7)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_Menikah)
                            .addComponent(rb_Mahsiswa))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        lbl_Judul.setText("Belajar Form Data Karyawan");
        txt_Hasil.setText("Namaku   =    "+txt_Nama.getText());
        txt_Hasil.append("\nTempat Lahir  =    "+txt_TempatLahir.getText());
        txt_Hasil.append("\nTTL =   "+txt_TTL.getText());
        txt_Hasil.append("\nPendidikan    =    "+cmb_Pendidikan.getSelectedItem());
        txt_Hasil.append("\nStatus    =    "+cmb_Status.getSelectedItem());        
               
        
        try {            
            
            
            if(rb_Menikah.isSelected()){
                Status_Diri = rb_Menikah.getText();
                
            }else if(rb_Mahsiswa.isSelected()){
                
                Status_Diri = rb_Mahsiswa.getText();
                
            }
            
            if(txt_Nama.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Isi Dulu Nama mu");
            }
            
            else if(txt_TempatLahir.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Isi Dulu Tempat Lahir mu");
            }
            else if(cmb_Pendidikan.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Pendidikan");
            }
            else if (Status_Diri == ""){
                JOptionPane.showMessageDialog(null, "Silahkan Pilih Status Diri");
            }
            else{
            
            
                String Query = " INSERT INTO `data_karyawan` (`Nama`, `Tempat_Lahir`, `TTL`, `Pendidikan`, `Status`, `Status_Diri`)"
                        + " VALUES "
                        + "(' "+ txt_Nama.getText() + "  ', '"+ txt_TempatLahir.getText()+ "', "
                        + "'"+txt_TTL.getText()+"', '"+cmb_Pendidikan.getSelectedItem()+"', "
                        + "'"+cmb_Status.getSelectedItem()+"', '"+Status_Diri+"') ";
                kon.stat.executeUpdate(Query);
                tampil();
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Error SQL : "+ e);
        }       
        
        
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void tbl_DataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DataKaryawanMouseClicked
        int row = tbl_DataKaryawan.getSelectedRow(); 
        // cek baris mana yang terpilih
        
        
        
        ID = Integer.parseInt(tbl_DataKaryawan.getModel().getValueAt(row, 0).toString());
        txt_Nama.setText(tbl_DataKaryawan.getModel().getValueAt(row, 1).toString());
        
        String namanya = tbl_DataKaryawan.getModel().getValueAt(row, 1).toString();
        txt_TempatLahir.setText(tbl_DataKaryawan.getModel().getValueAt(row, 2).toString());
        txt_TTL.setText(tbl_DataKaryawan.getModel().getValueAt(row, 3).toString());      
        
        cmb_Pendidikan.setSelectedItem(tbl_DataKaryawan.getModel().getValueAt(row, 4).toString());
        cmb_Status.setSelectedItem(tbl_DataKaryawan.getModel().getValueAt(row, 5).toString());
        
        
        
        if(tbl_DataKaryawan.getModel().getValueAt(row, 6).toString().equals("Menikah")){
            rb_Menikah.setSelected(true);
        }else if(tbl_DataKaryawan.getModel().getValueAt(row, 6).toString().equals("Mahasiswa")){
            rb_Mahsiswa.setSelected(true);
        }
        //ini untuk menampilkan data ke tempat lain
        form_DatKaryawan tempatlain = new form_DatKaryawan();     
        tempatlain.tampilkan_Nama(namanya);
        tempatlain.show();
        
    }//GEN-LAST:event_tbl_DataKaryawanMouseClicked

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        int edit = JOptionPane.showConfirmDialog(null, "Yakin Hapus Data ?" ,"Hapus", 
                JOptionPane.YES_NO_OPTION);
            if(edit == JOptionPane.YES_OPTION){
                try {            
                    if(rb_Menikah.isSelected()){
                        Status_Diri = rb_Menikah.getText();

                    }else if(rb_Mahsiswa.isSelected()){
                        Status_Diri = rb_Mahsiswa.getText();
                    }
                    String Q_edit = "UPDATE `data_karyawan` SET `Nama` = '"+txt_Nama.getText()+"',"
                            + " `Tempat_Lahir` = '"+txt_TempatLahir.getText()+"', "
                            + "`TTL` = '"+txt_TTL.getText()+"', `Pendidikan` = '"+cmb_Pendidikan.getSelectedItem()+"', "
                            + "`Status` = '"+cmb_Status.getSelectedItem()+"', "
                            + "`Status_Diri` = '"+Status_Diri+"' "
                            + "WHERE `data_karyawan`.`ID` = '"+ID+"'";
                    kon.stat.executeUpdate(Q_edit);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
                    tampil();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error Edit"+e);
                }
                
            }
            
        
        
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        int hapus = JOptionPane.showConfirmDialog(null, "Yakin Hapus Data ?" ,"Hapus", 
                JOptionPane.YES_NO_OPTION);
        
        if(hapus==JOptionPane.YES_OPTION){
            try {
                String Q_Hapus = "DELETE FROM `data_karyawan` WHERE `data_karyawan`.`ID` = '"+ID+ "'";
                kon.stat.executeUpdate(Q_Hapus);
                tampil();
                JOptionPane.showMessageDialog(this, "Data Terhapus");

            } catch (Exception e) {
                //tampilkan errormu disini
            }
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_CariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CariKeyTyped
         String cari = txt_Cari.getText();  
         if(cari != ""){
            DefaultTableModel model_tblKaryawan = new DefaultTableModel();
            model_tblKaryawan.addColumn("ID ");
            model_tblKaryawan.addColumn("Nama");
            model_tblKaryawan.addColumn("Tempat Lahir");
            model_tblKaryawan.addColumn("TTL");
            model_tblKaryawan.addColumn("Pendidikan");
            model_tblKaryawan.addColumn("Status");
            model_tblKaryawan.addColumn("Status Diri");
            tbl_DataKaryawan.setModel(model_tblKaryawan);
            try {
                kon.res = kon.stat.executeQuery("SELECT * FROM `data_karyawan` WHERE Nama LIKE '%"+cari+"%' ");
                while(kon.res.next()){  
                    model_tblKaryawan.addRow(new Object[]{
                        kon.res.getString(1),
                        kon.res.getString(2),
                        kon.res.getString(3),
                        kon.res.getString(4),
                        kon.res.getString(5),                                        
                        kon.res.getString(6),
                        kon.res.getString(7)
                    });
                    tbl_DataKaryawan.setModel(model_tblKaryawan);
                }


            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan Error : "+e);
            }
         }else{
             tampil();
         }
    }//GEN-LAST:event_txt_CariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_DataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_DataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JComboBox<String> cmb_Pendidikan;
    private javax.swing.JComboBox<String> cmb_Status;
    private javax.swing.ButtonGroup grup_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_7;
    private javax.swing.JLabel lbl_Judul;
    private javax.swing.JRadioButton rb_Mahsiswa;
    private javax.swing.JRadioButton rb_Menikah;
    private javax.swing.JTable tbl_DataKaryawan;
    private javax.swing.JTextField txt_Cari;
    private javax.swing.JTextArea txt_Hasil;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_TTL;
    private javax.swing.JTextField txt_TempatLahir;
    // End of variables declaration//GEN-END:variables
}
